name: Build and Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1

    - name: Build solution
      run: msbuild Text_Editor.sln /p:Configuration=Release

    - name: Zip published files
      uses: actions/upload-artifact@v3
      with:
        name: LikhaanTextEditor
        path: LikhaanTextEditor/bin/Release

  release:
    needs: build
    runs-on: windows-latest
    steps:
    - name: Download build artifact
      uses: actions/download-artifact@v3
      with:
        name: LikhaanTextEditor

    - name: Create a Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: 'v1.0.${{ github.run_number }}'
        release_name: 'Likhaan Text Editor v1.0.${{ github.run_number }}'
        draft: false
        prerelease: false

    - name: Upload build to Release
      uses: svenstaro/upload-release-action@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ./LikhaanTextEditor.zip
        asset_name: LikhaanTextEditor.zip
        tag: 'v1.0.${{ github.run_number }}'
